### ISSUE TITLE
Cannot SSH to my DX4000

### ISSUE THREAD

**Issue by Flip01002003** [alexhorner/WD-DX4000-Installer#10]
I'm having an issue SSH-ing into my DX4000. I have the NAS plugged into my TP-Link DECO node in my office via ethernet.

I started using Balena Etcher to write the Bookworm ISO to a flash drive. Once complete, I plugged it into the DX4000, hold the reset button, and power on. I hold the reset button until the LCD says "INITIALIZING OK, LOADING RECOVERY". I wait a few minutes for the device to come online.

Using Zenmap, I run nmap -sn 192.168.1.1/24, giving me all hosts with IP and MAC addresses. I find the MAC address for the DX4000 and note the IP address.

When I go to SSH to it, whether I use Powershell or Putty, I get a Connection Refused.

I thought it was an SSH configuration issue. I've uninstalled and reinstalled OpenSSH a few times, ensured the services are running, and created a firewall rule to allow traffic on port 22.

Checking on Zenmap, again, I run nmap -v 192.168.1.95 to check for open ports. Results say 1000 scanned ports, 1000 ports closed. 

Any guidance to help this along??

**Comment by alexhorner** [comment]
Hi @Flip01002003 

This might be the https://github.com/alexhorner/WD-DX4000-Installer?tab=readme-ov-file#pings-but-wont-ssh troubleshooting issue in the README. I will test it out on hardware for you later myself and report back.

Thanks

**Comment by Flip01002003** [comment]
It appears to be the same issue. I can ping but cannot SSH, so likely the same. I appreciate the quick response and look forward to any fixes/breakthroughs!

**Comment by alexhorner** [comment]
Issue has been confirmed and now resolved with an ISO rebuild: https://github.com/alexhorner/WD-DX4000-Installer/releases/tag/PR3r1

**Comment by Flip01002003** [comment]
You are a gentleman and a scholar. Thank you, sir!
