### ISSUE TITLE
Can Ping, can't SSH using PR3r1

### ISSUE THREAD

**Issue by plasticrake** [alexhorner/WD-DX4000-Installer#12]
Flashed PR3r1 [x4000-bookworm-installer.iso](https://github.com/alexhorner/WD-DX4000-Installer/releases/download/PR3r1/dx4000-bookworm-installer.iso) to a 16GB usb drive. It's the only drive connected. I see LOADING RECOVERY, I can ping after about 1 minute, but ssh just shows connection refused. Then the device powers itself off after about 5 minutes since boot. I tried 3 different ball point pens!

I see the device downloading from these IPs: 
64.50.233.100
64.50.236.52
208.80.154.139

Thank you so much for this guide and all this work! Hope I can get this working.

Thank you!

**Comment by alexhorner** [comment]
Hey there!

If you're getting Loading Recovery then your ballpoint pens are successfully pointing, that message means the button has been held correctly and it's doing a USB boot.

This is probably another case of the ISO going out of date as described in the readme. I can get a new version built and pushed for you tomorrow night (UK time)

**Comment by alexhorner** [comment]
Hopefully this one will work, please let me know! https://github.com/alexhorner/WD-DX4000-Installer/releases/tag/PR3r2

Thanks

**Comment by plasticrake** [comment]
Thank you so much! Unfortunately still having an issue. The first time I tried PR3r2, it worked and I was able to SSH in. But I cancelled the install before starting it. When I rebooted the device later when I was ready to install, I could not get back into SSH. I tried reflashing a few times and about 8 different reboots. Not sure if launching the installer did something or I had bad timing with whatever change you had to make to get it to work, debian has since updated again?

**Comment by plasticrake** [comment]
I let it sit for 30 minutes and the first boot up I was able to SSH. I was in the menus for partitioning and then it turned itself off. The next few boots it was turning off before even getting to "LOADING RECOVERY". I wonder if my unit is defective?

**Comment by plasticrake** [comment]
Wow, I took out the mainboard and the CPU heatsink was not attached! One of the retention pegs is completely missing. I guess its overheating and turning off. I got this thing secondhand... I'll close this issue for now and hopefully by the time I fix this the installer is still working. Cheers!

**Comment by alexhorner** [comment]
> Wow, I took out the mainboard and the CPU heatsink was not attached! One of the retention pegs is completely missing. I guess its overheating and turning off. I got this thing secondhand... I'll close this issue for now and hopefully by the time I fix this the installer is still working. Cheers!

Wowzers! Good thing you checked. I was gonna reply and say yea sounds like hardware failure.

Hopefully your little atom isn't cooked!
