### ISSUE TITLE
No network

### ISSUE THREAD

**Issue by jdbravo** [alexhorner/WD-DX4000-Installer#5]
Hello,

I ran the Bullseye/generate_images.sh and it generated the file outout/dx4000-bullseye-installer.iso. Is this file a 47Mb file or it didn't generate properly?

Then I used dd to transfer that iso to the USB drive: dd if=outout/dx4000-bullseye-installer.iso of=/dev/sdb

Then I inserted the USB drive in the WD-DX4000 and turned ON while pressing the reset button. It did show in the LCD "INITIALIZING OK, LOADING RECEOVERY" .

I see some activity in the NIC 1 on the WD-DX4000, but in the switch where it's connected the led is off and the DHCP server is not giving any IP.

Did I make something wrong?

Thank you!

**Comment by alexhorner** [comment]
Hi,

Please try using the released ISO file at https://github.com/alexhorner/WD-DX4000-Installer/releases

The latest is PR2 at the time of writing. It shouldn't be necessary to build your own unless you are modifying it.

It is likely an upstream kernel change has killed the ability to do an install, so I will need to build a new image. Therefore, please let me know regardless of whether you succeed or not. If it is broken, I can probably get you a new image released within a few hours.

**Comment by jdbravo** [comment]
Hey Alex, with the released ISO it did work!

thank you!
