### ISSUE TITLE
Step Installing GRUB boot loader fails

### ISSUE THREAD

**Issue by badgumby** [alexhorner/WD-DX4000-Installer#7]
I have attempted to install from the Debian Bullseye ISO (both your PR2r1 and a custom built using your scripts) and it fails when attemtping to run 'grub-install dummy'. I have tried several times with different flash drives and it always fails at this step. See screenshot attached. I'm not sure what else to try.
![grub-install fails](https://github.com/alexhorner/WD-DX4000-Installer/assets/28875386/33f319a1-a253-458f-a465-705d0fc4f552)

**Comment by badgumby** [comment]
Sure! The specs are below:

USB drive 1 (Install media): 8GB sandisk
USB drive 2 (permanent): 32GB sandisk
4 Drives in bays: The original Western Digital 2TB disks

**Comment by alexhorner** [comment]
Awesome, thanks,

So, I have encountered this before, and I found that the disks/partitions were an issue for me. I don't entirely know why the issue occurs, but the basic meaning behind `grub-install dummy` is that the installer failed to select an appropriate partition on which to install GRUB, and therefore selects a device called `dummy` which is of course useless and will fail.

Although I don't entirely know what causes the issue, I would recommend you try the following:
- Remove the 4 OEM disks from the bays for the installation
- Don't manually partition the system, or ensure an EFI boot partition in which GRUB can safely install exists
- If you need to partition the 4 OEM disks, do it after the system has fully booted into the new installation

Alternatively, you could try skipping GRUB's installation, and then chrooting into your new installation from the installer shell and manually installing GRUB from the CLI yourself, however I am aware EFI installations of GRUB are a nightmare and need some level of understanding and GRUB experience to complete.

If you need any further help, please don't hesitate to let me know!

**Comment by badgumby** [comment]
Thanks for the suggestions! I'll try removing the drives and reinstalling. There is currently nothing on this system, and at some point I plan on replacing the drives, but wanted to see if I could get this running on it first. I'll update you once I know more.

**Comment by badgumby** [comment]
Ok. I skipped the grub-install on the script and entered the chroot. I was then able to manually install grub.

![manual_grub](https://github.com/alexhorner/WD-DX4000-Installer/assets/28875386/25e18dfe-224f-43a2-aae4-81be32c504f0)

I was then able copy the `startup.nsh` to the root of the /dev/sdb1 and bounced the system. 
It is now working as expected! Thanks for your suggestion. I will close this issue.

**Comment by alexhorner** [comment]
Glad it worked out, thank you for updating us!
