### ISSUE TITLE
Won't boot; startup.nsh doesn't seem right

### ISSUE THREAD

**Issue by wrexroad** [alexhorner/WD-DX4000-Installer#8]
I've tried the installation a few times now and can't get it to boot afterwards. I have mounted the USB's boot partition and copied in the startup.nsh file, but it still doesn't work.
When I looked at startup.nsh it looks like it is pointing to EFI/debian/grubx64.efi but when I look in the boot partition I am finding efi/debian/grub.cfg. The grubx64.efi file is located under efi/boot/grubx64.efi. I tried changing the startup.nsh file, but it still didn't work. Honestly, I have no idea how this file works, so I could be way off base here, just grasping at straws really.
Any chance you will make a disk image available that already has the system installed and configured?

**Comment by alexhorner** [comment]
Hi @wrexroad, if you have some directory listings you could share that would be useful. It will be several hours before I'm able to look into this but ill do a test installation myself later and see what's going on

**Comment by wrexroad** [comment]
Here is what is on the boot partition:
```
/mnt # find ./
./
./efi
./efi/boot
./efi/boot/bootx64.efi
./efi/boot/grubx64.efi
./efi/debian
./efi/debian/grub.cfg
./startup.nsh
```
I noticed that when I tried to mount the boot partition on my ubuntu laptop it said that it was a bad filesystem. gparted also didn't recognize it. Then, when I restarted the DX4000, the boot partition was on sda2 instead of sda1.

**Comment by wrexroad** [comment]
Oh man, I'm dumb. That was the boot partition of the installation media. I can't get the boot partition of the destination drive to mount though...

**Comment by alexhorner** [comment]
These things happen! It sounds like the boot partition was created but never formatted. Did the installation actually succeed?

Did you manually partition the disk? I never have a very good time when doing so, you have to have an EFI partition and it has to be set up with the right flags and stuff, I rarely get it right, I recommend starting with some automatic partitioning or maybe if you can let it auto partition then edit the result without disturbing what it configured too much. If that fails let me know and I'll investigate further.

**Comment by wrexroad** [comment]
I used "Guided Partitioning (use entire disk)" and it appeared to succeed. I've included screen shots of what it looks like when gparted looks at the disk.

![Screenshot from 2024-01-12 01-41-08](https://github.com/alexhorner/WD-DX4000-Installer/assets/2264352/b012e852-c5b8-43e4-a4af-588ea6d6999c)

![Screenshot from 2024-01-12 01-41-04](https://github.com/alexhorner/WD-DX4000-Installer/assets/2264352/85d55673-f483-4c45-acdf-e01bc437b937)

One thing that that is a bit different is that I am using a micro sd card reader rather than a regular USB stick. I've used this for boot media in the past and never had an issue... but maybe?

I'll try to reinstall again tonight.

**Comment by wrexroad** [comment]
I tried reinstalling it again and I was able to add `startup.nsh` to the correct partition, but again it didn't boot. I pulled the drive and looked at it  on my laptop and the boot partition was corrupted. When I booted the installed again, it (unsurprisingly) couldn't mount the boot partition. So I changed the install media to a real SSD and everything worked.
Sorry for creating the issue, I guess it was all for nothing. Thanks so much for the work you put into this!

**Comment by alexhorner** [comment]
No worries! Sorry I haven't been too active on this one, you opened the issue right as I got really busy. Glad to hear you worked it out! Probably would have taken longer if I did attempt to help to be honest, I wouldn't have guessed bad installation media for a while.
